### PR TITLE
Fixes openrazer ebuild to function on 5.4 kernels

### PR DESCRIPTION
**Pull request by cockytrumpet**
Issue https://github.com/vifino/vifino-overlay/issues/22

Found through trial and error. This works with gentoo-sources-5.4.1.

### CODE REVIEW

**Comment by ppfeufer** [comment]
Confirmed, patch works

**Comment by vifino** [comment]
Hey @cockytrumpet, thanks for contributing!
Do you know if it still works with older kernels?

**Comment by cockytrumpet** [comment]
It builds against gentoo-4.19.86 just fine as well.

**Comment by vifino** [comment]
Merged. Thanks!

**Pull request merged**
