### PR TITLE
polychromatic update

### PR DESCRIPTION
**Pull request by ppfeufer**
app-misc/polychromatic updated to pull in dev-python/distro as dependency as mentioned in #24

### CODE REVIEW

**Comment by vifino** [comment]
Hey, thanks for the update! By the way, you should synchronise your fork with my master, it has diverging commits which clutter the PR. I'll squash and merge it, which'll end up with the same two files changed.

**Comment by ppfeufer** [comment]
I did sync with your master » https://github.com/ppfeufer/vifino-overlay/commit/050bd0d232ee05bc1ea7be13ea1885d1af225e8b

Don't ask me what actually went wrong there.

**Comment by vifino** [comment]
That's a new merge commit, which is not in my branch, so while it has the same content, it has a different history. Git makes things hard. :)
I think the easiest is to force push my branch to your branch, or delete your fork and refork, if you prefer it that way.

**Comment by ppfeufer** [comment]
Ya, the latter is probably what I do next time, since GitHub doesn't have a propper way to keep forks in sync ...

**Pull request merged**
